import { describe, expect, test } from "bun:test";
import { createGenerator, presetUno } from "unocss";
import { batch3Shortcuts } from "../src/shortcuts/batch3.ts";
import { batch3Rules } from "../src/rules/batch3.ts";
import {
  parseCss,
  resolveFor,
  themeVars,
  tvar,
  winningDecl,
} from "./compat.ts";

// Batch 3 standalone harness (does NOT use presetDaisy, so other batches'
// files stay untouched per task constraints).
// Composes a minimal test preset from batch3 shortcuts+rules with presetUno,
// mirroring cssFor() in tests/compat.ts.

type Opts = { prefix: string; include: string[]; exclude: string[] };

const baseOpts: Opts = { prefix: "", include: [], exclude: [] };

const batchCache = new Map<string, string>();

async function cssForBatch3(classes: string, opts: Opts = baseOpts): Promise<string> {
  const cacheKey = `${opts.prefix}|${classes}`;
  const hit = batchCache.get(cacheKey);
  if (hit !== undefined) return hit;
  // NOTE: separators:[':'] — Uno's default separators [':','-'] parse
  // `hover-gallery` as hover-variant + `gallery` and `link-primary` as
  // link-variant (`:link`) + `primary`, swallowing our exact upstream class
  // names. Restricting to ':' keeps `hover:`/`sm:` variants working while
  // letting `hover-*`/`link-*` match our shortcuts/rules byte-for-byte.
  const uno = await createGenerator({
    separators: [":"],
    presets: [
      presetUno(),
      {
        name: "batch3test",
        shortcuts: batch3Shortcuts(opts) as never,
        rules: batch3Rules(opts) as never,
      },
    ],
  });
  const { css } = await uno.generate(classes, { preflights: false });
  batchCache.set(cacheKey, css);
  return css;
}

// Every public class token demoed (see tests/fixtures/batch3-tokens.json).
// Child/marker tokens that have no standalone rule upstream (indicator-item,
// list-row, list-col-grow, mockup-browser-toolbar) are smoke-tested via the
// parent combo that emits their selector — the CSS is still generated by the
// standalone batch3test preset.
const SINGLE_TOKENS: string[] = [
  "hover-gallery",
  "indicator",
  "indicator-start",
  "indicator-center",
  "indicator-end",
  "indicator-top",
  "indicator-middle",
  "indicator-bottom",
  "kbd",
  "kbd-xs",
  "kbd-sm",
  "kbd-md",
  "kbd-lg",
  "kbd-xl",
  "label",
  "floating-label",
  "link",
  "link-hover",
  "link-primary",
  "link-secondary",
  "link-accent",
  "link-neutral",
  "link-info",
  "link-success",
  "link-warning",
  "link-error",
  "list",
  "list-col-wrap",
  "loading",
  "loading-spinner",
  "loading-dots",
  "loading-ring",
  "loading-ball",
  "loading-bars",
  "loading-infinity",
  "loading-xs",
  "loading-sm",
  "loading-md",
  "loading-lg",
  "loading-xl",
  "mask",
  "mask-half-1",
  "mask-half-2",
  "mask-squircle",
  "mask-decagon",
  "mask-diamond",
  "mask-heart",
  "mask-hexagon",
  "mask-hexagon-2",
  "mask-circle",
  "mask-pentagon",
  "mask-star",
  "mask-star-2",
  "mask-triangle",
  "mask-triangle-2",
  "mask-triangle-3",
  "mask-triangle-4",
  "megamenu",
  "megamenu-active",
  "megamenu-wide",
  "megamenu-full",
  "megamenu-vertical",
  "megamenu-xs",
  "megamenu-sm",
  "megamenu-md",
  "megamenu-lg",
  "megamenu-xl",
  "mockup-code",
  "mockup-window",
  "mockup-browser",
  "mockup-phone",
  "mockup-phone-camera",
  "mockup-phone-display",
  "navbar",
  "navbar-start",
  "navbar-center",
  "navbar-end",
];

const COMBO_TOKENS: Array<[string, string]> = [
  ["indicator-item", "indicator indicator-item"],
  ["list-row", "list list-row"],
  ["list-col-grow", "list list-row list-col-grow"],
  ["mockup-browser-toolbar", "mockup-browser mockup-browser-toolbar"],
];

describe("batch3 smoke: every public class generates CSS", () => {
  for (const tok of SINGLE_TOKENS) {
    test(tok, async () => {
      const css = await cssForBatch3(tok);
      expect(css.length).toBeGreaterThan(0);
      expect(css).toContain(`.${tok}`);
    });
  }
  for (const [tok, combo] of COMBO_TOKENS) {
    test(`${tok} (via "${combo}")`, async () => {
      const css = await cssForBatch3(combo);
      expect(css.length).toBeGreaterThan(0);
      // The combo's CSS must mention the token (in a :has/:where selector).
      expect(css).toContain(tok);
    });
  }
});

describe("batch3 hovergallery", () => {
  test("base sets --items:1 and grid template", async () => {
    const rules = parseCss(await cssForBatch3("hover-gallery"));
    expect(winningDecl(rules, ["hover-gallery"], "--items")?.value).toBe("1");
    expect(winningDecl(rules, ["hover-gallery"], "grid-template-columns")?.value).toBe(
      "repeat(var(--items), 1fr)",
    );
    expect(winningDecl(rules, ["hover-gallery"], "overflow")?.value).toBe("hidden");
  });
  test("nested counts and hover behavior emitted", async () => {
    const css = await cssForBatch3("hover-gallery");
    expect(css).toContain(":has(> :nth-child(3))");
    expect(css).toContain("--items:2");
    expect(css).toContain("--items:9");
    expect(css).toContain("display:inline-grid");
    expect(css).toContain("grid-column:1 / -1");
    expect(css).toContain("display:none");
  });
});

describe("batch3 indicator", () => {
  test("base is relative inline-flex max-content", async () => {
    const rules = parseCss(await cssForBatch3("indicator"));
    expect(winningDecl(rules, ["indicator"], "position")?.value).toBe("relative");
    expect(winningDecl(rules, ["indicator"], "display")?.value).toBe("inline-flex");
    expect(winningDecl(rules, ["indicator"], "width")?.value).toBe("max-content");
  });
  test("item positioning vars with defaults", async () => {
    const css = await cssForBatch3("indicator indicator-item");
    expect(css).toContain("indicator-item");
    expect(css).toContain("var(--indicator-t, 0)");
    expect(css).toContain("var(--indicator-x, 50%)");
  });
  test("start/center/end/top/middle/bottom set vars", async () => {
    const cases: Array<[string, string, string]> = [
      ["indicator-start", "--indicator-s", "0"],
      ["indicator-center", "--indicator-s", "50%"],
      ["indicator-end", "--indicator-x", "50%"],
      ["indicator-top", "--indicator-t", "0"],
      ["indicator-middle", "--indicator-t", "50%"],
      ["indicator-bottom", "--indicator-b", "0"],
    ];
    for (const [cls, prop, val] of cases) {
      const rules = parseCss(await cssForBatch3(cls));
      expect(winningDecl(rules, [cls], prop)?.value).toBe(val);
    }
  });
  test("rtl overrides emitted", async () => {
    const css = await cssForBatch3("indicator-start indicator-center indicator-end");
    expect(css).toContain('[dir="rtl"]');
  });
});

describe("batch3 kbd", () => {
  test("base uses base-200 bg and base-content fg", async () => {
    const vars = await themeVars("light");
    const rules = parseCss(await cssForBatch3("kbd"));
    expect(resolveFor(rules, ["kbd"], vars, winningDecl(rules, ["kbd"], "background-color")?.value ?? "")).toBe(
      tvar(vars, "--color-base-200"),
    );
    expect(resolveFor(rules, ["kbd"], vars, winningDecl(rules, ["kbd"], "color")?.value ?? "")).toBe(
      tvar(vars, "--color-base-content"),
    );
    expect(winningDecl(rules, ["kbd"], "border-radius")?.value).toBe("var(--radius-field)");
  });
  test("sizes match upstream numeric values", async () => {
    const expected: Record<string, [string, string]> = {
      "kbd-xs": ["calc(var(--size-selector, 0.25rem) * 4)", "0.625rem"],
      "kbd-sm": ["calc(var(--size-selector, 0.25rem) * 5)", "0.75rem"],
      "kbd-md": ["calc(var(--size-selector, 0.25rem) * 6)", "0.875rem"],
      "kbd-lg": ["calc(var(--size-selector, 0.25rem) * 7)", "1rem"],
      "kbd-xl": ["calc(var(--size-selector, 0.25rem) * 8)", "1.125rem"],
    };
    for (const [cls, [size, fs]] of Object.entries(expected)) {
      const rules = parseCss(await cssForBatch3(`kbd ${cls}`));
      expect(winningDecl(rules, ["kbd", cls], "--size")?.value).toBe(size);
      expect(winningDecl(rules, ["kbd", cls], "font-size")?.value).toBe(fs);
    }
  });
});

describe("batch3 label", () => {
  test("label is inline-flex with currentcolor 60%", async () => {
    const rules = parseCss(await cssForBatch3("label"));
    expect(winningDecl(rules, ["label"], "display")?.value).toBe("inline-flex");
    expect(winningDecl(rules, ["label"], "gap")?.value).toBe("0.375rem");
    expect(winningDecl(rules, ["label"], "color")?.value).toContain("60%");
  });
  test("label nests: has(input) cursor and input children", async () => {
    const css = await cssForBatch3("label");
    expect(css).toContain(":has(input)");
    expect(css).toContain("cursor:pointer");
    expect(css).toContain("calc(100% - 0.5rem)");
  });
  test("floating-label is relative flex with span behavior", async () => {
    const rules = parseCss(await cssForBatch3("floating-label"));
    expect(winningDecl(rules, ["floating-label"], "display")?.value).toBe("flex");
    expect(winningDecl(rules, ["floating-label"], "position")?.value).toBe("relative");
    const css = await cssForBatch3("floating-label");
    expect(css).toContain("::placeholder");
    expect(css).toContain("--top-mul");
    expect(css).toContain(":focus-within");
  });
});

describe("batch3 link colors resolve to theme values", () => {
  const COLORS = [
    "primary",
    "secondary",
    "accent",
    "neutral",
    "info",
    "success",
    "warning",
    "error",
  ] as const;
  for (const color of COLORS) {
    test(`light: link-${color}`, async () => {
      const classes = ["link", `link-${color}`];
      const vars = await themeVars("light");
      const rules = parseCss(await cssForBatch3(classes.join(" ")));
      const fg = winningDecl(rules, classes, "color");
      expect(fg).not.toBeNull();
      expect(resolveFor(rules, classes, vars, fg?.value ?? "")).toBe(tvar(vars, `--color-${color}`));
    });
    test(`dark: link-${color}`, async () => {
      const classes = ["link", `link-${color}`];
      const vars = await themeVars("dark");
      const rules = parseCss(await cssForBatch3(classes.join(" ")));
      const fg = winningDecl(rules, classes, "color");
      expect(fg).not.toBeNull();
      expect(resolveFor(rules, classes, vars, fg?.value ?? "")).toBe(tvar(vars, `--color-${color}`));
    });
  }
  test("link base is underline pointer", async () => {
    const rules = parseCss(await cssForBatch3("link"));
    expect(winningDecl(rules, ["link"], "text-decoration-line")?.value).toBe("underline");
    expect(winningDecl(rules, ["link"], "cursor")?.value).toBe("pointer");
  });
  test("link-hover is none with hover underline", async () => {
    const rules = parseCss(await cssForBatch3("link-hover"));
    expect(winningDecl(rules, ["link-hover"], "text-decoration-line")?.value).toBe("none");
    const css = await cssForBatch3("link-hover");
    expect(css).toContain(":hover");
    expect(css).toContain("text-decoration-line:underline");
  });
  test("link color hover darkens via color-mix", async () => {
    const css = await cssForBatch3("link link-primary");
    expect(css).toContain("color-mix(in oklab, var(--color-primary) 80%, #000)");
  });
});

describe("batch3 list", () => {
  test("list is flex column", async () => {
    const rules = parseCss(await cssForBatch3("list"));
    expect(winningDecl(rules, ["list"], "display")?.value).toBe("flex");
    expect(winningDecl(rules, ["list"], "flex-direction")?.value).toBe("column");
  });
  test("list-row grid emitted with divider", async () => {
    const css = await cssForBatch3("list list-row");
    expect(css).toContain("grid-template-columns:var(--list-grid-cols)");
    expect(css).toContain("border-color:color-mix(in oklab, var(--color-base-content) 5%, transparent)");
  });
  test("list-col-grow counts emitted", async () => {
    const css = await cssForBatch3("list");
    expect(css).toContain("list-col-grow:nth-child(1)");
    expect(css).toContain("--list-grid-cols:1fr");
    expect(css).toContain("grid-row-start:1");
  });
  test("list-col-wrap is row-start 2", async () => {
    const rules = parseCss(await cssForBatch3("list-col-wrap"));
    expect(winningDecl(rules, ["list-col-wrap"], "grid-row-start")?.value).toBe("2");
  });
});

describe("batch3 loading", () => {
  test("base is currentColor mask with spinner", async () => {
    const rules = parseCss(await cssForBatch3("loading"));
    expect(winningDecl(rules, ["loading"], "background-color")?.value).toBe("currentColor");
    expect(winningDecl(rules, ["loading"], "aspect-ratio")?.value).toBe("1");
    expect(winningDecl(rules, ["loading"], "mask-size")?.value).toBe("100%");
    expect(winningDecl(rules, ["loading"], "mask-image")?.value).toContain("data:image/svg+xml");
  });
  for (const v of ["spinner", "dots", "ring", "ball", "bars", "infinity"] as const) {
    test(`loading-${v} has mask-image`, async () => {
      const rules = parseCss(await cssForBatch3(`loading loading-${v}`));
      expect(winningDecl(rules, ["loading", `loading-${v}`], "mask-image")?.value).toContain(
        "data:image/svg+xml",
      );
    });
  }
  test("sizes match upstream numeric values", async () => {
    const expected: Record<string, string> = {
      "loading-xs": "calc(var(--size-selector, 0.25rem) * 4)",
      "loading-sm": "calc(var(--size-selector, 0.25rem) * 5)",
      "loading-md": "calc(var(--size-selector, 0.25rem) * 6)",
      "loading-lg": "calc(var(--size-selector, 0.25rem) * 7)",
      "loading-xl": "calc(var(--size-selector, 0.25rem) * 8)",
    };
    for (const [cls, width] of Object.entries(expected)) {
      const rules = parseCss(await cssForBatch3(`loading ${cls}`));
      expect(winningDecl(rules, ["loading", cls], "width")?.value).toBe(width);
    }
  });
});

describe("batch3 mask", () => {
  test("base is inline-block contain no-repeat center", async () => {
    const rules = parseCss(await cssForBatch3("mask"));
    expect(winningDecl(rules, ["mask"], "display")?.value).toBe("inline-block");
    expect(winningDecl(rules, ["mask"], "mask-size")?.value).toBe("contain");
    expect(winningDecl(rules, ["mask"], "mask-repeat")?.value).toBe("no-repeat");
    expect(winningDecl(rules, ["mask"], "mask-position")?.value).toBe("center");
  });
  test("half masks have 200% size with rtl flip", async () => {
    for (const cls of ["mask-half-1", "mask-half-2"] as const) {
      const rules = parseCss(await cssForBatch3(`mask ${cls}`));
      expect(winningDecl(rules, ["mask", cls], "mask-size")?.value).toBe("200%");
    }
    const css = await cssForBatch3("mask-half-1 mask-half-2");
    expect(css).toContain(":dir(rtl)");
  });
  for (const s of [
    "squircle",
    "decagon",
    "diamond",
    "heart",
    "hexagon",
    "hexagon-2",
    "circle",
    "pentagon",
    "star",
    "star-2",
    "triangle",
    "triangle-2",
    "triangle-3",
    "triangle-4",
  ] as const) {
    test(`mask-${s} has mask-image`, async () => {
      const rules = parseCss(await cssForBatch3(`mask mask-${s}`));
      expect(winningDecl(rules, ["mask", `mask-${s}`], "mask-image")?.value).toContain("data:image/svg+xml");
    });
  }
});

describe("batch3 megamenu", () => {
  test("base is flex with mm vars", async () => {
    const rules = parseCss(await cssForBatch3("megamenu"));
    expect(winningDecl(rules, ["megamenu"], "display")?.value).toBe("flex");
    expect(winningDecl(rules, ["megamenu"], "--mm-anchor")?.value).toBe("--mm1");
    expect(winningDecl(rules, ["megamenu"], "--size")?.value).toBe("calc(var(--size-field, 0.25rem) * 10)");
  });
  test("popovertarget/popover/has behavior emitted", async () => {
    const css = await cssForBatch3("megamenu megamenu-active");
    expect(css).toContain("[popovertarget]");
    expect(css).toContain("[popover]");
    expect(css).toContain("anchor-name:var(--mm-anchor)");
    expect(css).toContain(":popover-open");
  });
  test("active is absolute with base-content 10%", async () => {
    const rules = parseCss(await cssForBatch3("megamenu-active"));
    expect(winningDecl(rules, ["megamenu-active"], "position")?.value).toBe("absolute");
    expect(winningDecl(rules, ["megamenu-active"], "background-color")?.value).toContain(
      "var(--color-base-content)",
    );
  });
  test("sizes match upstream numeric values", async () => {
    const expected: Record<string, [string, string, string]> = {
      "megamenu-xs": ["0.6875rem", "0.5rem", "calc(var(--size-field, 0.25rem) * 6)"],
      "megamenu-sm": ["0.75rem", "0.75rem", "calc(var(--size-field, 0.25rem) * 8)"],
      "megamenu-md": ["0.875rem", "1rem", "calc(var(--size-field, 0.25rem) * 10)"],
      "megamenu-lg": ["1.125rem", "1.25rem", "calc(var(--size-field, 0.25rem) * 12)"],
      "megamenu-xl": ["1.375rem", "1.5rem", "calc(var(--size-field, 0.25rem) * 14)"],
    };
    for (const [cls, [fs, p, size]] of Object.entries(expected)) {
      const rules = parseCss(await cssForBatch3(`megamenu ${cls}`));
      expect(winningDecl(rules, ["megamenu", cls], "--fontsize")?.value).toBe(fs);
      expect(winningDecl(rules, ["megamenu", cls], "--mm-p")?.value).toBe(p);
      expect(winningDecl(rules, ["megamenu", cls], "--size")?.value).toBe(size);
    }
  });
});

describe("batch3 mockup", () => {
  test("mockup-code uses neutral colors", async () => {
    const vars = await themeVars("light");
    const rules = parseCss(await cssForBatch3("mockup-code"));
    expect(resolveFor(rules, ["mockup-code"], vars, winningDecl(rules, ["mockup-code"], "background-color")?.value ?? "")).toBe(
      tvar(vars, "--color-neutral"),
    );
    expect(resolveFor(rules, ["mockup-code"], vars, winningDecl(rules, ["mockup-code"], "color")?.value ?? "")).toBe(
      tvar(vars, "--color-neutral-content"),
    );
  });
  test("code/window/browser/phone nests emitted", async () => {
    const css = await cssForBatch3("mockup-code mockup-window mockup-browser mockup-phone");
    expect(css).toContain("box-shadow:1.4em 0, 2.8em 0, 4.2em 0");
    expect(css).toContain("data-prefix");
    expect(css).toContain("mockup-browser-toolbar");
    expect(css).toContain("corner-shape:superellipse");
  });
  test("phone camera/display grid placement", async () => {
    const cam = parseCss(await cssForBatch3("mockup-phone-camera"));
    expect(winningDecl(cam, ["mockup-phone-camera"], "grid-column")?.value).toBe("1 / 1");
    const disp = parseCss(await cssForBatch3("mockup-phone-display"));
    expect(winningDecl(disp, ["mockup-phone-display"], "overflow")?.value).toBe("hidden");
    expect(winningDecl(disp, ["mockup-phone-display"], "border-radius")?.value).toBe("54px");
  });
  test("phone frame matches upstream", async () => {
    const rules = parseCss(await cssForBatch3("mockup-phone"));
    expect(winningDecl(rules, ["mockup-phone"], "border")?.value).toBe("5px solid #6b6b6b");
    expect(winningDecl(rules, ["mockup-phone"], "max-width")?.value).toBe("462px");
    expect(winningDecl(rules, ["mockup-phone"], "aspect-ratio")?.value).toBe("462 / 978");
  });
});

describe("batch3 navbar", () => {
  test("navbar is flex full width 4rem", async () => {
    const rules = parseCss(await cssForBatch3("navbar"));
    expect(winningDecl(rules, ["navbar"], "display")?.value).toBe("flex");
    expect(winningDecl(rules, ["navbar"], "width")?.value).toBe("100%");
    expect(winningDecl(rules, ["navbar"], "min-height")?.value).toBe("4rem");
  });
  test("sections layout", async () => {
    const s = parseCss(await cssForBatch3("navbar-start"));
    expect(winningDecl(s, ["navbar-start"], "width")?.value).toBe("50%");
    expect(winningDecl(s, ["navbar-start"], "justify-content")?.value).toBe("flex-start");
    const c = parseCss(await cssForBatch3("navbar-center"));
    expect(winningDecl(c, ["navbar-center"], "flex-shrink")?.value).toBe("0");
    const e = parseCss(await cssForBatch3("navbar-end"));
    expect(winningDecl(e, ["navbar-end"], "justify-content")?.value).toBe("flex-end");
  });
  test(":where navbar relative emitted", async () => {
    const css = await cssForBatch3("navbar");
    expect(css).toContain(":where(.navbar)");
    expect(css).toContain("position:relative");
  });
});

describe("batch3 prefix and include/exclude", () => {
  test("prefix d- renames", async () => {
    const css = await cssForBatch3("d-hover-gallery d-kbd d-link d-navbar", {
      prefix: "d-",
      include: [],
      exclude: [],
    });
    expect(css).toContain(".d-hover-gallery");
    expect(css).toContain(".d-kbd");
    expect(css).toContain(".d-link");
    expect(css).toContain(".d-navbar");
  });
  test("exclude filters components", async () => {
    const css = await cssForBatch3("hover-gallery kbd", {
      prefix: "",
      include: [],
      exclude: ["hovergallery"],
    });
    expect(css).not.toContain(".hover-gallery{");
    expect(css).toContain(".kbd");
  });
  test("include filters components", async () => {
    const css = await cssForBatch3("link mask", {
      prefix: "",
      include: ["link"],
      exclude: [],
    });
    expect(css).toContain(".link");
    expect(css).not.toContain(".mask{");
  });
});
