// Canonical daisyUI theme order (hard fork of daisyui@v5.7.43).
// Source: packages/daisyui/functions/themeOrder.js — verbatim order, never
// hand-edit. `src/theme/themes.css` banner order (`--- <name> ---`) matches
// this list; `tests/docs-chrome.test.ts` locks the two in sync.
// Docs fork (`docs/src/lib/themes.js`, generated by
// `docs/scripts/syncThemes.js`) consumes this list so the docs theme
// switcher needs no `daisyui` package at runtime.
export const themeOrder: string[] = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
  "caramellatte",
  "abyss",
  "silk",
];
