// Generated by `bun run tokens`. Do not hand-edit oklch values.
// Bridge: upstream CSS vars (src/themes/*.css) -> Uno theme.extend.colors
// TODO(P2): fill via scripts/generate-tokens.ts from daisyui@5.7.43
export function daisyTheme(_opts: { themes: string[] | false }): Record<string, any> {
  return {
    extend: {
      colors: {
        // primary: 'var(--color-primary)',
        // 'primary-content': 'var(--color-primary-content)',
        // 'base-100': 'var(--color-base-100)',
        // ...all 35 themes share the same var names; themes.css swaps values
      },
    },
  }
}
